title: Sensory Bridge
description: A music visualizer from the future!
theme: just-the-docs

url: https://connornishijima.github.io/sensory_bridge_docs

logo: "/img/product.png"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
