title: emotiscope
description: a music visualizer from the future
theme: just-the-docs

url: "https://lixie-labs.github.io/emotiscope-site"

#logo: "/img/product.png"

# Color scheme supports "light" (default) and "dark"
color_scheme: bridge

ga_tracking: G-1C3WX4V60G
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

callouts_level: quiet

callouts:
  warning:
    title: WATCH OUT!
    color: red
  highlight:
    title: PLEASE NOTE
    color: yellow
  info:
    title: JUST SO YOU KNOW
    color: grey-lt
  glow:
    title:  
    color: grey-dk

aux_links:
  "<link-out>JUMP TO APP</link-out>":
    - "https://app.emotiscope.rocks/"

# External navigation links
nav_external_links:
  - title: App
    url: https://app.emotiscope.rocks
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
  - title: Twitter
    url: https://twitter.com/lixielabs
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Mastodon
    url: https://leds.social/@lixielabs
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Threads
    url: https://threads.net/@lixielabs
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
