title: SENSORY BRIDGE
description: A music visualizer from the future!
theme: just-the-docs

url: https://connornishijima.github.io/sensory_bridge_docs

#logo: "/img/product.png"

# Color scheme supports "light" (default) and "dark"
color_scheme: bridge

callouts_level: quiet

callouts:
  warning:
    title: WATCH OUT!
    color: red
  highlight:
    title: PLEASE NOTE
    color: yellow
  info:
    title: JUST SO YOU KNOW
    color: grey-lt

aux_links:
  "<link-out>More From Lixie Labs</link-out>":
    - "https://lectronz.com/stores/lixielabs"

# External navigation links
nav_external_links:
  - title: Settings
    url: https://settings.sensorybridge.rocks
    hide_icon: true # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
