title: SENSORY BRIDGE
description: A music visualizer from the future!
theme: just-the-docs

url: https://connornishijima.github.io/sensory_bridge_docs

#logo: "/img/product.png"

# Color scheme supports "light" (default) and "dark"
color_scheme: bridge

ga_tracking: G-1C3WX4V60G
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

callouts_level: quiet

callouts:
  warning:
    title: WATCH OUT!
    color: red
  highlight:
    title: PLEASE NOTE
    color: yellow
  info:
    title: JUST SO YOU KNOW
    color: grey-lt

aux_links:
  "<link-out>More From Lixie Labs</link-out>":
    - "https://lectronz.com/stores/lixielabs"

# External navigation links
nav_external_links:
  - title: Settings
    url: https://settings.sensorybridge.rocks
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Troubleshoot
    url: https://troubleshoot.sensorybridge.rocks
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: YouTube
    url: https://youtube.com/user/connornishijima
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Mastodon
    url: https://leds.social/lixielabs
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Threads
    url: https://threads.net/lixielabs
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
