title: Sensory Bridge
description: A music visualizer from the future!
theme: just-the-docs

url: https://connornishijima.github.io/sensory_bridge_docs

#logo: "/img/product.png"

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

aux_links:
  More From Lixie Labs: https://github.com/connornishijima
