title: SENSORY BRIDGE
description: A music visualizer from the future!
theme: just-the-docs

url: https://connornishijima.github.io/sensory_bridge_docs

#logo: "/img/product.png"

# Color scheme supports "light" (default) and "dark"
color_scheme: bridge

callouts:
  warning:
    title: WATCH OUT!
    color: red
  highlight:
    title: PLEASE NOTE
    color: yellow
  info:
    title: JUST SO YOU KNOW
    color: purple

aux_links:
  "<link-out>More From Lixie Labs</link-out>":
    - "https://github.com/connornishijima"
